#!/bin/bash

declare -a HAPPY_STRINGS=(
    "Have a wonderful day!"
    "Keep up the great work!"
    "Go get 'em tiger!"
    "Thanks for playing!"
    "Follow your dreams!"
)

get_stash_list () {
    echo $(git --no-pager stash list | cut -d':' -f1)
}

bounce () {
    n=$((RANDOM % ${#HAPPY_STRINGS[@]}))
    printf "${HAPPY_STRINGS[n]}\n"
    exit 0
}

stash_list=$(get_stash_list)

if [[ $stash_list == "" ]]; then
    echo "Nothing to do here, stash is empty!"
    bounce
fi

curr_stash=0
num_stashes=$(wc -w <<< $stash_list)
while [[ $curr_stash -lt $num_stashes ]]; do
    printf "Stash $curr_stash:\n"
    git stash show $curr_stash

    go_next=0
    while [[ $go_next -eq 0 ]]; do
        printf "(I)nspect (P)op, (D)rop, (A)pply, (S)kip, (Q)uit?: "
        read -n 1 choice
        printf "\n"

        case $choice in
            [Ii])
                git stash show -p $s
                ;;
            [Pp])
                printf "Popping $s\n\n"
                git stash pop $s
                num_stashes=$((num_stashes-1))
                go_next=1
                ;;
            [Dd])
                printf "Dropping $s\n\n"
                git stash drop $s
                num_stashes=$((num_stashes-1))
                go_next=1
                ;;
            [Aa])
                printf "Applying $s\n\n"
                git stash apply $s
                curr_stash=$((curr_stash+1))
                go_next=1
                ;;
            [Ss])
                printf "Skipping $s\n\n"
                curr_stash=$((curr_stash+1))
                go_next=1
                ;;
            [Ll])
                printf "You can pop and drop it but you can't lock it, sorry\n\n"
                ;;
            [Qq])
                bounce
        esac
    done
done
